services:
  bot:
    container_name: beatdock
    image: ghcr.io/lazaroagomez/beatdock:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - beatdock-network
    env_file: .env

networks:
  beatdock-network:
    name: beatdock_network
