services:
  bot:
    container_name: vovaplayer
    image: ghcr.io/lazaroagomez/vovaplayer:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - vovaplayer-network

networks:
  vovaplayer-network:
    name: vovaplayer_network
